In [6]:
import torch
x = torch.empty(5, 3)
x

tensor([[ 0.0000e+00,  2.0000e+00, -6.7076e+21],
        [ 4.6577e-10,  1.1210e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [7]:
x = torch.rand(5, 3)
x

tensor([[0.9804, 0.6990, 0.0382],
        [0.7376, 0.8244, 0.3625],
        [0.3233, 0.5794, 0.2350],
        [0.1171, 0.4982, 0.5526],
        [0.3233, 0.1613, 0.3041]])

In [8]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [9]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
x = x.new_ones(5, 3, dtype=torch.float64)
x


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [11]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-1.8212,  0.9351, -0.8975],
        [-0.1464,  0.4804, -0.4417],
        [ 1.7609, -0.3312, -0.2145],
        [-1.7894, -1.6312, -0.2785],
        [-0.4103,  0.1828, -0.5633]])

In [18]:
y = torch.rand(5, 3)
x + y
torch.add(x, y)
y.add_(x)
x

tensor([[ 1.1788,  3.9351,  2.1025],
        [-0.1464,  0.4804, -0.4417],
        [ 1.7609, -0.3312, -0.2145],
        [-1.7894, -1.6312, -0.2785],
        [-0.4103,  0.1828, -0.5633]])

### Index

In [19]:
y = x[0, :]
print(y)
print(x)
y += 1
print(y)
print(x[0, :])

tensor([1.1788, 3.9351, 2.1025])
tensor([[ 1.1788,  3.9351,  2.1025],
        [-0.1464,  0.4804, -0.4417],
        [ 1.7609, -0.3312, -0.2145],
        [-1.7894, -1.6312, -0.2785],
        [-0.4103,  0.1828, -0.5633]])
tensor([2.1788, 4.9351, 3.1025])
tensor([2.1788, 4.9351, 3.1025])


In [21]:
y = x.view(15)
y

tensor([ 2.1788,  4.9351,  3.1025, -0.1464,  0.4804, -0.4417,  1.7609, -0.3312,
        -0.2145, -1.7894, -1.6312, -0.2785, -0.4103,  0.1828, -0.5633])

In [25]:
z = x.view(-1, 5) # -1所指的纬度可以根据其他纬度的值推算出来
z

tensor([[ 2.1788,  4.9351,  3.1025, -0.1464,  0.4804],
        [-0.4417,  1.7609, -0.3312, -0.2145, -1.7894],
        [-1.6312, -0.2785, -0.4103,  0.1828, -0.5633]])

In [26]:
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [28]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[ 1.1788,  3.9351,  2.1025],
        [-1.1464, -0.5196, -1.4417],
        [ 0.7609, -1.3312, -1.2145],
        [-2.7894, -2.6312, -1.2785],
        [-1.4103, -0.8172, -1.5633]])
tensor([ 2.1788,  4.9351,  3.1025, -0.1464,  0.4804, -0.4417,  1.7609, -0.3312,
        -0.2145, -1.7894, -1.6312, -0.2785, -0.4103,  0.1828, -0.5633])


### 线性代数
* 函数	     功能
* trace	  对角线元素之和(矩阵的迹)
* diag	  对角线元素
* triu/tril 矩阵的上三角/下三角，可指定偏移量
* mm/bmm	  矩阵乘法，batch的矩阵乘法
* addmm/addbmm/addmv/addr/baddbmm..	矩阵运算
* t	      转置
* dot/cross 内积/外积
* inverse	  求逆矩阵
* svd       奇异值分解

In [29]:
x = torch.arange(1, 3).view(1, 2)
x

tensor([[1, 2]])

In [30]:
y = torch.arange(1, 4).view(3, 1)
y

tensor([[1],
        [2],
        [3]])

In [32]:
# 广播机制
print(x)
print(y)
x + y # x中的元素被广播

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])


tensor([[2, 3],
        [3, 4],
        [4, 5]])

In [33]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before)

False


In [35]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before)

True


In [36]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add(_x)
print(id(y) == id_before)

True


### Tensor and Numpy

In [37]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


In [38]:
a += 1
print(a, b)
b += 1
print(a, b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [39]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [40]:
a += 1
print(a, b)
b += 1
print(a, b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [41]:
c = torch.tensor(a)
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [63]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))
else:
    print("cuda_not_available")

cuda_not_available
