In [17]:
import numpy as np
np_data = np.array([[1,2,3],[4,5,6],[1,3,5],[2,4,6]])
np_data

array([[1, 2, 3],
       [4, 5, 6],
       [1, 3, 5],
       [2, 4, 6]])

In [18]:
np.sum(np_data, axis=0)

array([ 8, 14, 20])

In [19]:
np.sum(np_data, axis=1)

array([ 6, 15,  9, 12])

In [20]:
np.min(np_data, axis=0)

array([1, 2, 3])

In [38]:
np_data = np.random.randint(0, 6, [4,2,3,4])
np_data

array([[[[5, 4, 0, 0],
         [3, 5, 0, 5],
         [2, 1, 2, 3]],

        [[2, 2, 1, 4],
         [3, 2, 2, 4],
         [0, 3, 3, 5]]],


       [[[0, 5, 4, 2],
         [4, 5, 1, 0],
         [2, 0, 5, 3]],

        [[0, 1, 4, 2],
         [4, 1, 0, 3],
         [2, 1, 3, 5]]],


       [[[5, 1, 1, 3],
         [1, 3, 1, 5],
         [1, 5, 1, 5]],

        [[5, 3, 1, 2],
         [3, 3, 0, 1],
         [0, 1, 0, 4]]],


       [[[2, 3, 0, 2],
         [0, 2, 5, 0],
         [1, 4, 3, 5]],

        [[5, 3, 1, 1],
         [5, 0, 5, 4],
         [3, 0, 1, 5]]]])

In [48]:
np_data.sum(axis=3)

array([[[ 9, 13,  8],
        [ 9, 11, 11]],

       [[11, 10, 10],
        [ 7,  8, 11]],

       [[10, 10, 12],
        [11,  7,  5]],

       [[ 7,  7, 13],
        [10, 14,  9]]])

In [31]:
np_data = np.array(
    [
        [
            [1, 2, 3], 
            [2, 3, 4]
        ],
        [
            [3, 4, 5],
            [6, 7, 8]
        ]
    ]
    )
np_data

array([[[1, 2, 3],
        [2, 3, 4]],

       [[3, 4, 5],
        [6, 7, 8]]])

In [32]:
np_data.sum(axis=0)

array([[ 4,  6,  8],
       [ 8, 10, 12]])

In [33]:
np_data.sum(axis=1)

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [34]:
np_data.sum(axis=2)

array([[ 6,  9],
       [12, 21]])

In [36]:
np_data.sum(axis=-1)

array([[ 6,  9],
       [12, 21]])